import { useState } from 'react';
import { useProject } from '@/contexts/ProjectContext';
import { Milestone } from '@/types/project';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Separator } from '@/components/ui/separator';
import { FileText, Copy, Check } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';

function getMilestoneProgress(m: Milestone): number {
  if (m.tasks.length === 0) return 0;
  return Math.round((m.tasks.filter(t => t.status === 'completed').length / m.tasks.length) * 100);
}

export default function ReportsPage() {
  const { project } = useProject();
  const { toast } = useToast();
  const [copied, setCopied] = useState(false);

  const today = new Date();
  const allTasks = project.milestones.flatMap(m => m.tasks);
  const completedTasks = allTasks.filter(t => t.status === 'completed');
  const overdueTasks = allTasks.filter(t => new Date(t.dueDate) < today && t.status !== 'completed');
  const inProgressTasks = allTasks.filter(t => t.status === 'in-progress');
  const blockedTasks = allTasks.filter(t => t.status === 'blocked');
  const openRisks = project.risks.filter(r => r.status === 'open').sort((a, b) => b.probability * b.impact - a.probability * a.impact);
  const overallProgress = project.milestones.length > 0
    ? Math.round(project.milestones.reduce((s, m) => s + getMilestoneProgress(m), 0) / project.milestones.length)
    : 0;

  const healthLabel = project.healthStatus === 'green' ? '🟢 On Track' : project.healthStatus === 'yellow' ? '🟡 At Risk' : '🔴 Off Track';

  const report = `# Weekly Status Report — ${project.name}
**Date:** ${today.toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric', year: 'numeric' })}
**Project Health:** ${healthLabel}
**Overall Progress:** ${overallProgress}%

---

## Executive Summary

${project.name} is currently ${healthLabel.slice(2).toLowerCase()}. ${completedTasks.length} of ${allTasks.length} tasks are complete (${overallProgress}% overall progress). ${overdueTasks.length > 0 ? `**${overdueTasks.length} task(s) are overdue** and require immediate attention.` : 'All tasks are on schedule.'} ${blockedTasks.length > 0 ? `${blockedTasks.length} task(s) are currently blocked.` : ''}

## Milestone Status

${project.milestones.map(m => {
  const p = getMilestoneProgress(m);
  const statusEmoji = m.status === 'completed' ? '✅' : m.status === 'in-progress' ? '🔄' : m.status === 'blocked' ? '🚫' : '⬜';
  return `- ${statusEmoji} **${m.name}** — ${p}% complete (${m.tasks.filter(t => t.status === 'completed').length}/${m.tasks.length} tasks)`;
}).join('\n')}

## This Week's Progress

${inProgressTasks.length > 0 ? inProgressTasks.map(t => `- ${t.title} (${t.owner})`).join('\n') : '- No tasks currently in progress'}

## Upcoming Work

${allTasks.filter(t => t.status === 'not-started').sort((a, b) => new Date(a.dueDate).getTime() - new Date(b.dueDate).getTime()).slice(0, 5).map(t => `- ${t.title} — due ${new Date(t.dueDate).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })} (${t.owner})`).join('\n') || '- No upcoming tasks'}

${overdueTasks.length > 0 ? `## ⚠ Overdue Items

${overdueTasks.map(t => `- **${t.title}** — was due ${new Date(t.dueDate).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })} (${t.owner}, ${t.priority} priority)`).join('\n')}` : ''}

${blockedTasks.length > 0 ? `## 🚫 Blockers

${blockedTasks.map(t => `- **${t.title}** (${t.owner})`).join('\n')}` : ''}

## Risk Summary

${openRisks.length > 0 ? openRisks.slice(0, 5).map(r => `- **${r.title}** — Score: ${r.probability * r.impact}/25, Owner: ${r.owner}${r.probability * r.impact >= 15 ? ' ⚠ HIGH RISK' : ''}`).join('\n') : '- No open risks'}

## Key Decisions Made

${project.decisions.length > 0 ? project.decisions.slice(0, 3).map(d => `- **${d.title}** (${new Date(d.date).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}) — ${d.chosen}. _${d.rationale.slice(0, 100)}${d.rationale.length > 100 ? '...' : ''}_`).join('\n') : '- No decisions recorded this period'}

## Decisions Needed

${blockedTasks.length > 0 ? blockedTasks.map(t => `- Resolution needed for blocked task: **${t.title}**`).join('\n') : '- No decisions pending'}${openRisks.filter(r => new Date(r.reviewDate) <= new Date(Date.now() + 7 * 86400000)).length > 0 ? '\n' + openRisks.filter(r => new Date(r.reviewDate) <= new Date(Date.now() + 7 * 86400000)).map(r => `- Risk review due: **${r.title}** (${new Date(r.reviewDate).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })})`).join('\n') : ''}

---

_Generated by AI Project Command Center_`;

  const handleCopy = () => {
    navigator.clipboard.writeText(report);
    setCopied(true);
    toast({ title: 'Report copied to clipboard' });
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold tracking-tight text-foreground">Weekly Status Report</h1>
          <p className="text-sm text-muted-foreground">Executive-ready summary generated from your project data</p>
        </div>
        <Button onClick={handleCopy} size="sm">
          {copied ? <Check className="w-4 h-4 mr-1" /> : <Copy className="w-4 h-4 mr-1" />}
          {copied ? 'Copied' : 'Copy Report'}
        </Button>
      </div>

      <Card className="border shadow-sm">
        <CardHeader className="pb-3">
          <CardTitle className="text-sm font-semibold flex items-center gap-2">
            <FileText className="w-4 h-4 text-muted-foreground" />
            Report Preview
          </CardTitle>
        </CardHeader>
        <Separator />
        <CardContent className="pt-6">
          <div className="prose prose-sm max-w-none">
            {report.split('\n').map((line, i) => {
              if (line.startsWith('# ')) return <h1 key={i} className="text-xl font-bold text-foreground mt-0 mb-2">{line.slice(2)}</h1>;
              if (line.startsWith('## ')) return <h2 key={i} className="text-base font-semibold text-foreground mt-6 mb-2">{line.slice(3)}</h2>;
              if (line.startsWith('---')) return <Separator key={i} className="my-4" />;
              if (line.startsWith('**') && line.includes(':**')) {
                const [label, ...rest] = line.split(':**');
                return <p key={i} className="text-sm mb-1"><strong className="text-foreground">{label.replace(/\*/g, '')}:</strong> {rest.join(':**').replace(/\*/g, '')}</p>;
              }
              if (line.startsWith('- ')) {
                const content = line.slice(2)
                  .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
                  .replace(/_(.*?)_/g, '<em>$1</em>');
                return <p key={i} className="text-sm text-foreground pl-4 mb-1 before:content-['•'] before:mr-2 before:text-muted-foreground" dangerouslySetInnerHTML={{ __html: content }} />;
              }
              if (line.startsWith('_') && line.endsWith('_')) return <p key={i} className="text-xs text-muted-foreground italic mt-4">{line.slice(1, -1)}</p>;
              if (line.trim() === '') return <div key={i} className="h-2" />;
              const content = line.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>');
              return <p key={i} className="text-sm text-foreground mb-1" dangerouslySetInnerHTML={{ __html: content }} />;
            })}
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
